camunda.bpm:
  admin-user:
    id: u
    password: u
    firstName:
  filter:
    create: All tasks
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2
#url for console of database: http://localhost:8085/h2
server:
  port: 8085

